export const browserCoreExamples = [
  "soloclaw browser status",
  "soloclaw browser start",
  "soloclaw browser stop",
  "soloclaw browser tabs",
  "soloclaw browser open https://example.com",
  "soloclaw browser focus abcd1234",
  "soloclaw browser close abcd1234",
  "soloclaw browser screenshot",
  "soloclaw browser screenshot --full-page",
  "soloclaw browser screenshot --ref 12",
  "soloclaw browser snapshot",
  "soloclaw browser snapshot --format aria --limit 200",
  "soloclaw browser snapshot --efficient",
  "soloclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "soloclaw browser navigate https://example.com",
  "soloclaw browser resize 1280 720",
  "soloclaw browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "soloclaw browser press Enter",
  "soloclaw browser hover 44",
  "soloclaw browser drag 10 11",
  "soloclaw browser select 9 OptionA OptionB",
  "soloclaw browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "soloclaw browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "soloclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "soloclaw browser console --level error",
  "soloclaw browser pdf",
];
